FROM arm32v7/node

# set timezone
ENV TZ America/Toronto
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/hue-mqtt-bridge

RUN git clone git://github.com/dale3h/hue-mqtt-bridge.git . \
	&& npm install

RUN sed -i \
	-e "s/^var config = require.+$/var config = require('/data/config.json');/" \
	index.js

CMD [ "/bin/bash", "-c", "if [ ! -e /data/config.json ]; then cp -a ./config.sample.json /data/config.json; fi; node index.js" ]

