FROM arm32v7/node:slim

# set timezone
ENV TZ America/Toronto
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN npm install -g hue2mqtt

CMD [ "hue2mqtt", "-b", "192.168.86.131", "-m", "mqtt://192.168.86.13", "-p", "1", "-d"]

